import React, { useState, useEffect, useMemo } from 'react';
import { 
  Shield, Lock, Calendar, Clock, Settings, Check, ChevronRight, 
  Car, MapPin, Phone, MessageCircle, User, FileText, 
  RefreshCcw, Eye, EyeOff, Menu, X, Users, Award, 
  Edit3, Trash2, CheckCircle, AlertTriangle, Plus, Minus, Smartphone, AlertOctagon, Map, Key, Mail, Save, XCircle, Search, ChevronLeft, ChevronRight as ChevronRightIcon, Globe
} from 'lucide-react';
import { initializeApp } from 'firebase/app';
import { 
  getAuth, signInAnonymously, onAuthStateChanged 
} from 'firebase/auth';
import { 
  getFirestore, collection, addDoc, onSnapshot, 
  doc, updateDoc, deleteDoc, query, orderBy, serverTimestamp, where, getDocs 
} from 'firebase/firestore';

// --- CONFIGURATION ---
const firebaseConfig = {
  apiKey: "AIzaSyDPZQhv_Ox_FytpDR_jUbsyWMzcPa_xxk",
  authDomain: "new-chitwan-driving.firebaseapp.com",
  projectId: "new-chitwan-driving",
  storageBucket: "new-chitwan-driving.firebasestorage.app",
  messagingSenderId: "538552281062",
  appId: "1:538552281062:web:b6f756314ff53acch11827"
};

// --- INITIALIZATION ---
let auth: any = {}; 
let db: any = {}; 
let firebaseError: string | null = null; 

try {
  const app = initializeApp(firebaseConfig);
  auth = getAuth(app);
  // Silently sign in the user so they can write to the database without OTP
  signInAnonymously(auth).catch((error) => console.error("Auth Error:", error));
  
  db = getFirestore(app);
} catch (err: any) {
  console.error("Firebase Init Error:", err);
  firebaseError = err.message;
}

const appId = 'new-chitwan-v1'; 

// --- LANGUAGE DATA ---
const dictionary: { [key: string]: { [key: string]: string } } = {
    'en': {
        'Home': 'Home', 
        'Book Training': 'Book Training', 
        'About Us': 'About Us', 
        'Contact': 'Contact',
        'Est. 2003': 'Est. 2003', 
        'Driving Training Centre': 'Driving Training Centre', 
        'Learn to Drive...': 'Learn to Drive with Confidence in Chitwan',
        'High Pass Rate': 'High Pass Rate', 
        'Expert Instructors': 'Expert Instructors', 
        'Well Maintained': 'Well Maintained',
        'Check Progress': 'Check Progress', 
        'New Booking': 'New Booking', 
        'Student Progress Check': 'Student Progress Check',
        'Enter Phone Number': 'Enter Phone Number', 
        'Active Courses': 'Active Courses', 
        'Next Class': 'Next Class',
        'Course Progress': 'Course Progress', 
        'Send Info': 'Send Info', 
        'Call': 'Call', 
        'Pending': 'Pending',
        'Active': 'Active', 
        'Add Private': 'Add Private', 
        'Settings': 'Settings', 
        'Logout': 'Logout',
        'Review Schedule': 'View Schedule', 
        'Save': 'Save', 
        'Reject': 'Reject', 
        'Review': 'Review',
        'Total Days': 'Total Days', 
        'First Session': 'First Session', 
        'Total Price': 'Total Price',
        'Address': 'Address', 
        'Bharatpur Address': 'Bharatpur Height, Chitwan (Same building as Eye Express)',
        'Phone Numbers': 'Phone Numbers', 
        'Email': 'Email', 
        'Get Directions': 'Get Directions (Google Maps)',
        'Owner Access Only': 'Owner Access Only', 
        'Forgot PIN?': 'Forgot PIN?', 
        'Reset PIN': 'Reset PIN',
        'Security Question': 'Security Question', 
        'Update Prices': 'Update Prices', 
        'Price Settings': 'Price Settings (NPR)',
        'Private Booking': 'Add Custom Private Booking', 
        'Go to Calendar': 'Go to Calendar',
        'Duration': 'Duration', 
        'Daily Time': 'Daily Time', 
        'Client Name': 'Client Name', 
        'Client Phone': 'Client Phone',
        'Price': 'Price', 
        'Date & Time': 'Date & Time', 
        'Update Question/Answer': 'Update Question/Answer',
        'SIMULATION MODE (Real SMS blocked in Preview)': 'SIMULATION MODE (Real SMS blocked in Preview)',
        'Use code:': 'Use code:', 
        'Incorrect Code. Try 123456.': 'Incorrect Code. Try 123456.',
        'Back to Dates': 'Back to Dates', 
        'Appointment Date': 'Appointment Date', 
        'Choose Time': 'Choose Time',
        'Change Time': 'Change Time', 
        'Instructor': 'Instructor', 
        'Your Name': 'Your Name', 
        'Mobile Number': 'Mobile Number',
        'Verify & Submit': 'Confirm Booking', 
        'Verifying...': 'Saving...', 
        'Confirm Booking': 'Confirm Booking',
        'Wrong Number?': 'Wrong Number?', 
        'Full Course Schedule': 'Full Course Schedule',
        'Close': 'Close', 
        'View Schedule': 'View Schedule', 
        'Remove': 'Remove', 
        'Edit Schedule': 'Edit Schedule',
        'Back': 'Back', 
        'Course': 'Course', 
        'days total': 'days total', 
        'Req': 'Req.',
        'Same Time Daily': 'Same Time Daily', 
        'Different Times': 'Different Times', 
        'Select Time': 'Select Time',
        'Continue to Verification': 'Continue', 
        'Review & Save': 'Review & Save',
        'Save New Schedule': 'Save New Schedule', 
        'Start Over': 'Start Over', 
        'Cancel': 'Cancel',
        'Same time for all sessions, or different times?': 'Same time for all sessions, or different times?',
        'sessions': 'sessions',
        'Please enter valid name and phone number': 'Please enter valid name and phone number',
        'Private (1 Day)': 'Private (1 Day)', 
        'Private Course': 'Private Course', 
        'Trial Preparation (1 Day)': 'Trial Preparation (1 Day)',
        'PIN must be at least 4 digits': 'PIN must be at least 4 digits',
        'To be scheduled': 'To be scheduled',
        'Update PIN': 'Update PIN',
        'Our History': 'Our History', 
        'Our Team': 'Our Team',
        'days selected': 'days selected',
        'Selected': 'Selected', 
        'Configure your course on the left': 'Configure your course on the left',
        'to proceed.': 'to proceed.',
        'Estimated Total': 'Estimated Total', 
        'Time Preference': 'Time Preference',
        'This time will be applied to all': 'This time will be applied to all', 
        'selected days.': 'selected days.',
        'Set Times for Each Day': 'Set Times for Each Day', 
        'times set.': 'times set.',
        'Client': 'Client', 
        'Day': 'Day',
        'What is the name of your first pet?': 'What is the name of your first pet?',
        'of': 'of',
        'Booking Details': 'Booking Details', 
        'days at': 'days at', 
        'Custom Times': 'Custom Times',
        'Request Sent!': 'Request Sent!', 
        'Prem Sir will review your request shortly.': 'Prem Sir will review your request shortly.',
        'Select': 'Select', 
        'Days': 'Days', 
        'Choose Date': 'Choose Date', 
        'No booking found for this number.': 'No booking found for this number.',
        'No active (approved) booking found for this number.': 'No active booking found for this number.',
        'No new requests.': 'No new requests.', 
        'No active students.': 'No active students.', 
        'Edit Booking': 'Edit Booking',
        'Save to Active Schedule': 'Save to Active Schedule', 
        'Change Login PIN': 'Change Login PIN', 
        'Current PIN': 'Current PIN',
        'Recovery Question Setup': 'Recovery Question Setup', 
        'Recovery Answer': 'Recovery Answer', 
        'Connection Error': 'Connection Error',
        'Your Answer': 'Your Answer', 
        'Enter your new PIN code': 'Enter your new PIN code', 
        'New PIN': 'New PIN', 
        'Verify Answer': 'Verify Answer',
        'Save New PIN': 'Save New PIN', 
        'Back to Login': 'Back to Login', 
        'Security & Price Settings': 'Security & Price Settings',
        'Notes (e.g. Family Discount, Cash Paid)': 'Notes (e.g. Family Discount, Cash Paid)', 
        'Name Required': 'Name Required',
        'Please select dates for the booking.': 'Please select dates for the booking.', 
        'Please select a time for every selected date.': 'Please select a time for every selected date.',
        'Private Booking Added to Active Schedule!': 'Private Booking Added to Active Schedule!', 
        'Price (Override)': 'Price (Override)',
        'Error removing booking: ': 'Error removing booking: ', 
        'Your driving course is confirmed!': 'Your driving course is confirmed!',
        'Package': 'Package', 
        'Location': 'Location', 
        'Please arrive 5 minutes early for your first session.': 'Please arrive 5 minutes early for your first session.',
        'Namaste': 'Namaste', 
        'Sunday': 'Sunday', 'Monday': 'Monday', 'Tuesday': 'Tuesday', 'Wednesday': 'Wednesday', 'Thursday': 'Thursday', 'Friday': 'Friday', 'Saturday': 'Saturday',
        'January': 'January', 'February': 'February', 'March': 'March', 'April': 'April', 'May': 'May', 'June': 'June', 'July': 'July', 'August': 'August', 'September': 'September', 'October': 'October', 'November': 'November', 'December': 'December',
        'Sun': 'Sun', 'Mon': 'Mon', 'Tue': 'Tue', 'Wed': 'Wed', 'Thu': 'Thu', 'Fri': 'Fri', 'Sat': 'Sat',
        'Other / Any Available': 'Other / Any Available', 
        'Delete this?': 'Delete this?', 
        'Active Schedule': 'Active Schedule',
        'Question/Answer must be long enough.': 'Question/Answer must be long enough.', 
        'Security Question/Answer Updated!': 'Security Question/Answer Updated!',
        'Database not ready': 'Database not ready', 
        'Error saving: ': 'Error saving: ', 
        'Check My Progress': 'Check My Progress',
        'Saving...': 'Saving...',
    },
    'ne': {
        'Home': 'मुख्य पृष्ठ', 
        'Book Training': 'बुकिङ गर्नुहोस्', 
        'About Us': 'हाम्रो बारेमा', 
        'Contact': 'सम्पर्क',
        'Est. 2003': 'स्था. २०६०', 
        'Driving Training Centre': 'ड्राइभिङ तालिम केन्द्र', 
        'Learn to Drive...': 'चितवनमा आत्मविश्वासका साथ ड्राइभिङ सिक्नुहोस्',
        'High Pass Rate': 'उच्च सफलता दर', 
        'Expert Instructors': 'विशेषज्ञ प्रशिक्षक', 
        'Well Maintained': 'सुसज्जित सवारी',
        'Check Progress': 'प्रगति हेर्नुहोस्', 
        'New Booking': 'नयाँ बुकिङ', 
        'Student Progress Check': 'विद्यार्थीको प्रगति जाँच',
        'Enter Phone Number': 'फोन नम्बर प्रविष्ट गर्नुहोस्', 
        'Active Courses': 'सक्रिय कक्षाहरू', 
        'Next Class': 'अर्को कक्षा',
        'Course Progress': 'प्रगति', 
        'Send Info': 'जानकारी पठाउनुहोस्', 
        'Call': 'कल गर्नुहोस्', 
        'Pending': 'बाँकी बुकिङ',
        'Active': 'सक्रिय बुकिङ', 
        'Add Private': 'निजी बुकिङ थप्नुहोस्', 
        'Settings': 'सेटिङहरू', 
        'Logout': 'बाहिर निस्कनुहोस्',
        'Review Schedule': 'तालिका हेर्नुहोस्', 
        'Save': 'सुरक्षित गर्नुहोस्', 
        'Reject': 'अस्वीकार गर्नुहोस्', 
        'Review': 'समीक्षा गर्नुहोस्',
        'Total Days': 'जम्मा दिन', 
        'First Session': 'पहिलो कक्षा', 
        'Total Price': 'कुल मूल्य',
        'Address': 'ठेगाना', 
        'Bharatpur Address': 'भरतपुर हाइट, चितवन (आई एक्सप्रेस भवन)',
        'Phone Numbers': 'फोन नम्बरहरू', 
        'Email': 'ईमेल', 
        'Get Directions': 'दिशा निर्देशन (गुगल नक्सा)',
        'Owner Access Only': 'मालिकको पहुँच मात्र', 
        'Forgot PIN?': 'पिन बिर्सनुभयो?', 
        'Reset PIN': 'पिन रिसेट गर्नुहोस्',
        'Security Question': 'सुरक्षा प्रश्न', 
        'Update Prices': 'मूल्य अपडेट गर्नुहोस्', 
        'Price Settings': 'मूल्य सेटिङहरू (रु)',
        'Private Booking': 'निजी बुकिङ थप्नुहोस्', 
        'Go to Calendar': 'क्यालेन्डरमा जानुहोस्',
        'Duration': 'अवधि', 
        'Daily Time': 'दैनिक समय', 
        'Client Name': 'ग्राहकको नाम', 
        'Client Phone': 'ग्राहकको फोन',
        'Price': 'मूल्य', 
        'Date & Time': 'मिति र समय', 
        'Update Question/Answer': 'प्रश्न/उत्तर अपडेट गर्नुहोस्',
        'SIMULATION MODE (Real SMS blocked in Preview)': 'सिमुलेशन मोड (प्रिभ्यूमा एसएमएस रोकिएको छ)',
        'Use code:': 'कोड प्रयोग गर्नुहोस्:', 
        'Incorrect Code. Try 123456.': 'गलत कोड। 123456 प्रयास गर्नुहोस्।',
        'Back to Dates': 'मितिमा फर्कनुहोस्', 
        'Appointment Date': 'बुकिङ मिति', 
        'Choose Time': 'समय छान्नुहोस्',
        'Change Time': 'समय परिवर्तन गर्नुहोस्', 
        'Instructor': 'प्रशिक्षक', 
        'Your Name': 'तपाईंको नाम', 
        'Mobile Number': 'मोबाइल नम्बर',
        'Verify & Submit': 'पुष्टि गरी बुझाउनुहोस्', 
        'Verifying...': 'पुष्टि गर्दै...', 
        'Confirm Booking': 'बुकिङ निश्चित गर्नुहोस्',
        'Wrong Number?': 'गलत नम्बर?', 
        'Full Course Schedule': 'पूर्ण कक्षा तालिका',
        'Close': 'बन्द गर्नुहोस्', 
        'View Schedule': 'तालिका हेर्नुहोस्', 
        'Remove': 'हटाउनुहोस्', 
        'Edit Schedule': 'तालिका सम्पादन गर्नुहोस्',
        'Back': 'पछाडि', 
        'Course': 'कोर्स', 
        'days total': 'दिन कुल', 
        'Req': 'अनुरोध',
        'Same Time Daily': 'दैनिक एउटै समय', 
        'Different Times': 'फरक फरक समय', 
        'Select Time': 'समय छान्नुहोस्',
        'Continue to Verification': 'पुष्टिका लागि अगाडि बढ्नुहोस्', 
        'Review & Save': 'समीक्षा गरी सुरक्षित गर्नुहोस्',
        'Save New Schedule': 'नयाँ तालिका सुरक्षित गर्नुहोस्', 
        'Start Over': 'फेरि सुरु गर्नुहोस्', 
        'Cancel': 'रद्द गर्नुहोस्',
        'Same time for all sessions, or different times?': 'सबै कक्षा एउटै समयमा वा फरक समयमा?',
        'sessions': 'कक्षाहरू',
        'Please enter valid name and phone number': 'कृपया वैध नाम र फोन नम्बर प्रविष्ट गर्नुहोस्',
        'Private (1 Day)': 'निजी (१ दिन)', 
        'Private Course': 'निजी कोर्स', 
        'Trial Preparation (1 Day)': 'परीक्षण तयारी (१ दिन)',
        'PIN must be at least 4 digits': 'पिन कम्तीमा ४ अंकको हुनुपर्छ',
        'To be scheduled': 'तालिका बनाउन बाँकी',
        'Update PIN': 'पिन अपडेट गर्नुहोस्',
        'Our History': 'हाम्रो इतिहास', 
        'Our Team': 'हाम्रो टोली',
        'days selected': 'दिन छानियो',
        'Selected': 'छानिएको', 
        'Configure your course on the left': 'बायाँपट्टि आफ्नो कोर्स सेट गर्नुहोस्',
        'to proceed.': 'अगाडि बढ्नका लागि।',
        'Estimated Total': 'अनुमानित कुल', 
        'Time Preference': 'समय प्राथमिकता',
        'This time will be applied to all': 'यो समय सबैमा लागू हुनेछ', 
        'selected days.': 'छानिएका दिनहरूमा।',
        'Set Times for Each Day': 'प्रत्येक दिनको समय सेट गर्नुहोस्', 
        'times set.': 'समय सेट भयो।',
        'Client': 'ग्राहक', 
        'Day': 'दिन',
        'What is the name of your first pet?': 'तपाईंको पहिलो पाल्तु जनावरको नाम के हो?',
        'of': 'को', 
        'Booking Details': 'बुकिङ विवरण', 
        'days at': 'दिनहरू, समय:', 
        'Custom Times': 'कस्टम समय',
        'Request Sent!': 'अनुरोध पठाइयो!', 
        'Prem Sir will review your request shortly.': 'प्रेम सरले चाँडै तपाईंको अनुरोध समीक्षा गर्नुहुनेछ।',
        'Select': 'छान्नुहोस्', 
        'Days': 'दिनहरू', 
        'Choose Date': 'मिति छान्नुहोस्', 
        'No booking found for this number.': 'यो नम्बरको लागि कुनै बुकिङ भेटिएन।',
        'No active (approved) booking found for this number.': 'यो नम्बरको लागि कुनै सक्रिय बुकिङ भेटिएन।',
        'No new requests.': 'कुनै नयाँ अनुरोध छैन।', 
        'No active students.': 'कुनै सक्रिय विद्यार्थी छैनन्।', 
        'Edit Booking': 'बुकिङ सम्पादन गर्नुहोस्',
        'Save to Active Schedule': 'सक्रिय तालिकामा बचत गर्नुहोस्', 
        'Change Login PIN': 'लगइन पिन परिवर्तन गर्नुहोस्', 
        'Current PIN': 'हालको पिन',
        'Recovery Question Setup': 'पुनर्प्राप्ति प्रश्न सेटअप', 
        'Recovery Answer': 'पुनर्प्राप्ति उत्तर', 
        'Connection Error': 'जडान त्रुटि',
        'Your Answer': 'तपाईंको उत्तर', 
        'Enter your new PIN code': 'तपाईंको नयाँ पिन कोड प्रविष्ट गर्नुहोस्', 
        'New PIN': 'नयाँ पिन', 
        'Verify Answer': 'उत्तर पुष्टि गर्नुहोस्',
        'Save New PIN': 'नयाँ पिन बचत गर्नुहोस्', 
        'Back to Login': 'लगइनमा फर्कनुहोस्', 
        'Security & Price Settings': 'सुरक्षा र मूल्य सेटिङहरू',
        'Notes (e.g. Family Discount, Cash Paid)': 'नोटहरू (जस्तै: पारिवारिक छुट, नगद भुक्तानी)', 
        'Name Required': 'नाम आवश्यक छ',
        'Please select dates for the booking.': 'कृपया बुकिङका लागि मितिहरू छान्नुहोस्।', 
        'Please select a time for